spring.application.name=GC-SpringAI-Agent

# 服务端口
server.port=8080
# 智普 AI 基础配置
spring.ai.zhipuai.api-key=xxx
spring.ai.zhipuai.base-url=https://open.bigmodel.cn/api/paas
# Embedding 模型配置（用于文本向量化）
spring.ai.zhipuai.embedding.options.model=embedding-2
# Chat 模型配置（用于生成回答）
spring.ai.zhipuai.chat.options.model=GLM-4-Flash



# Milvus 向量数据库配置



# Milvus 连接配置
spring.ai.vectorstore.milvus.client.host=127.0.0.1
spring.ai.vectorstore.milvus.client.port=19530

# 数据库名称（默认 default）
spring.ai.vectorstore.milvus.database-name=default
# 向量集合名称（自定义，不存在会自动创建）
spring.ai.vectorstore.milvus.collection-name=guide_exam_store
# 是否自动初始化 Schema（建议开启）
spring.ai.vectorstore.milvus.initialize-schema=true
# 向量维度（与智普 AI embedding-2 模型一致，为 1024）
spring.ai.vectorstore.milvus.embedding-dimension=1024

# 日志配置（便于调试）
logging.level.org.springframework.ai=INFO
logging.level.com.example=DEBUG